# Generated by Django 4.1 on 2023-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubnetIpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.GenericIPAddressField()),
                ('ipaddress', models.GenericIPAddressField()),
                ('machine', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='IpAddress',
        ),
    ]
