# Generated by Django 4.1 on 2023-08-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_subnetipaddress_delete_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnetipaddress',
            name='subnet',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
