# Generated by Django 4.1 on 2023-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_alter_subnetipaddress_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnetipaddress',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
