# Generated by Django 4.1 on 2023-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0006_alter_subnetipaddress_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnet',
            name='master_subnet',
        ),
        migrations.AlterField(
            model_name='subnet',
            name='subnet',
            field=models.CharField(help_text='Enter a valid CIDR notation (e.g., 192.168.0.0/24)', max_length=100),
        ),
    ]
