# Generated by Django 4.1 on 2023-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0007_remove_subnet_master_subnet_alter_subnet_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
